# Generated by Django 5.1.4 on 2024-12-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aluno_forma_conclusao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='forma_conclusao',
            field=models.CharField(max_length=100),
        ),
    ]
