# Generated by Django 5.1.4 on 2024-12-10 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_aluno_forma_conclusao'),
    ]

    operations = [
        migrations.CreateModel(
            name='MestreDeJogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('experiencia', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('classe', models.CharField(max_length=50)),
                ('nivel', models.IntegerField()),
                ('mestre_de_jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mestredejogo')),
            ],
        ),
        migrations.DeleteModel(
            name='Aluno',
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
    ]
