# Generated by Django 5.1.4 on 2024-12-11 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_mestredejogo_experiencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogador',
            name='classe',
            field=models.CharField(max_length=100),
        ),
    ]
